name: ThonkCrafting
main: com.epherical.crafting.ThonkCrafting
version: "1.0.0"
author: Thonk
description: Crafting Plugin that uses NMS registries to create crafting recipes
api-version: "1.16"
depend:
  - ProtocolLib
load: POSTWORLD
commands:
  recipe:
    usage: Used to edit or view a recipe.
  create:
    usage: Used to create a recipe.
  remove:
    usage: Remove a recipe so it can't be crafted.
permissions:
  thonkcrafting.view.allrecipes:
    description: Players with this permission will be able to view any recipe that exists on the server, even if they haven't discovered it yet.
    default: op
  thonkcrafting.edit.recipe:
    default: op
    description: Players with this permission can edit a recipe.